[network]
address = "127.0.0.1"
port = 8880

[template]
index_file = "index.html"

[service]
limit = 50
root = "/srv/repo/"
# Supports following values: "none", "chroot", "landlock"
# "chroot" requires root privileges to run the server.
# "landlock" requires newer kernel but don't need root privileges.
# When set to "none", yadex can not make sure that users can not access files outside the root directory.
# For example, a symlink pointing outside the root directory can be accessed.
security = "landlock"
# Whether to use template.index_file to render users the index.
# Accessed directly at /path/to/directory/
template_index = true
# Provide JSON API at /api/files endpoint.
json_api = true
